{
 "title": "Arqui",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "artillery-node, artillery-gunicorn"
   },
   {
    "name": "container",
    "query": "tp1-arquitectura_node_1, tp1-arquitectura_node_2, tp1-arquitectura_node_3, tp1-arquitectura_cadvisor_1, tp1-arquitectura_grafana_1, tp1-arquitectura_graphite_1, tp1-arquitectura_gunicorn_1, tp1-arquitectura_nginx_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.rps.count, 'Requests attempted')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Requests completed')"
    },
    {
     "target": "alias(stats.gauges.$server.scenariosCompleted, 'scenariosLaunched')"
    }
   ]
  },
  {
   "title": "Scenarios created (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenariosCreated)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioDuration.max)"
    },
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioDuration.min)"
    },
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioDuration.median)"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p99, 'p99')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p95, 'p95')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 10737418240), 'Memory')"
    }
   ]
  }
 ]
}